FROM node:lts-alpine

# Set working directory
WORKDIR /usr/app

# Only copy dependency definitions first
# include package-lock.json if available
COPY ["package.json", "package-lock.json", "./"] 

# Use npm ci if lock file is present, it's faster and more reliable
RUN npm ci || npm install

# Then copy the rest of your project
COPY . .

# Run the app
CMD ["npm", "run", "start"]
