FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Only copy dependency definitions first
COPY package.json .

RUN npm install

# Then copy the rest of your project
COPY . .

# Run the app
CMD ["npm", "run", "start"]
