name: Deploy Docker React Demo
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t kaylin.develop/react-test -f Dockerfile.dev .
      - run: docker run -e CI=true kaylin.develop/react-test npm test
